#creation de notre loadbalancing
- name: III.1/ Creation du loadbalancer
  local_action:
    module: ec2_elb_lb
    name: tibo-balancer
    security_group_ids: "{{ ec2securitygroup.group_id }}"
    region: "{{aws_region}}"
    scheme: internet-facing
    state: present
    subnets:
      - subnet-d9bd4f80
      - subnet-3f0e1c17
      - subnet-e9e183d3
      - subnet-19c2126e
    listeners:
      - protocol: http
        load_balancer_port: 80
        instance_port: 80

#Attacher chaques instances au load balancer
- name: III.2/ Ajout des instances a ELB
  local_action:
    module: ec2_elb
    region: "{{aws_region}}"
    ec2_elbs: "tibo-balancer"
    instance_id: "{{ item.id }}"
    state: present
  with_items: ec2.instances
